trigger: none

pool:
  name: LaptopPool

steps:
- task: AzureKeyVault@2
  displayName: Fetch secrets from Key Vault
  inputs:
    azureSubscription: web-app
    KeyVaultName: devops-vault-sirish
    SecretsFilter: DB_PASSWORD
    RunAsPreJob: true

- script: |
    echo "Secret key name: DB_PASSWORD"
    echo "Secret value: $(DB_PASSWORD)"
  displayName: Echo secret (value will be masked)

