trigger: none
pool:
  name: LaptopPool
steps:
  - task: AzureKeyVault@2
    displayName: Fetch secrets from Key Vault
    inputs:
      azureSubscription: demo-devops-service-connection
      KeyVaultName: devops-vault-sirish
      SecretsFilter: DBPASSWORD
      RunAsPreJob: true
  - script: |
      echo "Secret key name: DBPASSWORD"
      echo "Secret value: $(DBPASSWORD)"
      displayName: Echo secret (value will be masked)